<?php

namespace Ayigi\PlateFormeBundle\Repository;
use Ayigi\EtablissementBundle\Entity\Etablissement;
use Ayigi\PlateFormeBundle\Entity\Service;

/**
 * TarifServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TarifServiceRepository extends \Doctrine\ORM\EntityRepository
{

    public function getFaisMontant(Etablissement $etablissement, Service $service)
    {

        $q = $this->createQueryBuilder('ts')
            ->select('ts.montant')
            ->where('ts.etablissement = :etablissement')
            ->andWhere('ts.service = :service')
            ->setParameter('etablissement', $etablissement)
            ->setParameter('service', $service);

        return $q->getQuery()->getSingleResult();
    }
}
